type CampaignDifficulty = "Easy" | "Medium" | "Hard" | "Wizard";
type CampaignFoldDirection = "left" | "right" | "up" | "down";
type CampaignOptionKind = "correct" | "near-miss" | "wrong-punch";

type CampaignPoint = Readonly<{
  x: number;
  y: number;
}>;

export type CampaignRoundSpec = Readonly<{
  difficulty: CampaignDifficulty;
  folds: readonly CampaignFoldDirection[];
  punch: CampaignPoint;
  options: readonly (readonly CampaignPoint[])[];
  optionKinds: readonly CampaignOptionKind[];
  correctIndex: number;
  hiddenFoldIndex?: number;
}>;

// Frozen, reviewed Campaign corpus. Runtime code derives and validates every
// folded state and correct answer from these authored prompt and option specs.
export const CAMPAIGN_ROUND_SPECS = [
  {"difficulty":"Easy","folds":["left"],"punch":{"x":5,"y":2},"options":[[{"x":2,"y":2},{"x":5,"y":2}],[{"x":6,"y":1},{"x":2,"y":2}],[{"x":2,"y":1},{"x":5,"y":1}],[{"x":1,"y":2},{"x":6,"y":2}]],"optionKinds":["correct","near-miss","wrong-punch","wrong-punch"],"correctIndex":0},
  {"difficulty":"Easy","folds":["down"],"punch":{"x":2,"y":0},"options":[[{"x":3,"y":0},{"x":2,"y":7}],[{"x":2,"y":0},{"x":2,"y":7}],[{"x":3,"y":0},{"x":3,"y":7}],[{"x":2,"y":1},{"x":2,"y":6}]],"optionKinds":["near-miss","correct","wrong-punch","wrong-punch"],"correctIndex":1},
  {"difficulty":"Easy","folds":["up"],"punch":{"x":0,"y":6},"options":[[{"x":0,"y":1},{"x":1,"y":5}],[{"x":1,"y":1},{"x":1,"y":6}],[{"x":0,"y":1},{"x":0,"y":6}],[{"x":0,"y":0},{"x":0,"y":7}]],"optionKinds":["near-miss","wrong-punch","correct","wrong-punch"],"correctIndex":2},
  {"difficulty":"Easy","folds":["up"],"punch":{"x":4,"y":6},"options":[[{"x":4,"y":1},{"x":3,"y":7}],[{"x":4,"y":0},{"x":4,"y":7}],[{"x":3,"y":1},{"x":3,"y":6}],[{"x":4,"y":1},{"x":4,"y":6}]],"optionKinds":["near-miss","wrong-punch","wrong-punch","correct"],"correctIndex":3},
  {"difficulty":"Easy","folds":["right"],"punch":{"x":2,"y":0},"options":[[{"x":2,"y":0},{"x":6,"y":1}],[{"x":2,"y":0},{"x":5,"y":0}],[{"x":3,"y":0},{"x":4,"y":0}],[{"x":2,"y":1},{"x":5,"y":1}]],"optionKinds":["near-miss","correct","wrong-punch","wrong-punch"],"correctIndex":1},
  {"difficulty":"Easy","folds":["left"],"punch":{"x":4,"y":7},"options":[[{"x":2,"y":6},{"x":4,"y":7}],[{"x":2,"y":7},{"x":5,"y":7}],[{"x":3,"y":6},{"x":4,"y":6}],[{"x":3,"y":7},{"x":4,"y":7}]],"optionKinds":["near-miss","wrong-punch","wrong-punch","correct"],"correctIndex":3},
  {"difficulty":"Easy","folds":["down"],"punch":{"x":5,"y":1},"options":[[{"x":5,"y":1},{"x":5,"y":6}],[{"x":4,"y":1},{"x":5,"y":6}],[{"x":4,"y":1},{"x":4,"y":6}],[{"x":5,"y":0},{"x":5,"y":7}]],"optionKinds":["correct","near-miss","wrong-punch","wrong-punch"],"correctIndex":0},
  {"difficulty":"Easy","folds":["right"],"punch":{"x":2,"y":1},"options":[[{"x":2,"y":1},{"x":5,"y":2}],[{"x":2,"y":2},{"x":5,"y":2}],[{"x":2,"y":1},{"x":5,"y":1}],[{"x":1,"y":1},{"x":6,"y":1}]],"optionKinds":["near-miss","wrong-punch","correct","wrong-punch"],"correctIndex":2},
  {"difficulty":"Easy","folds":["up"],"punch":{"x":3,"y":5},"options":[[{"x":2,"y":2},{"x":3,"y":5}],[{"x":2,"y":2},{"x":2,"y":5}],[{"x":3,"y":3},{"x":3,"y":4}],[{"x":3,"y":2},{"x":3,"y":5}]],"optionKinds":["near-miss","wrong-punch","wrong-punch","correct"],"correctIndex":3},
  {"difficulty":"Easy","folds":["left"],"punch":{"x":7,"y":2},"options":[[{"x":0,"y":2},{"x":7,"y":2}],[{"x":1,"y":1},{"x":7,"y":2}],[{"x":0,"y":1},{"x":7,"y":1}],[{"x":0,"y":3},{"x":7,"y":3}]],"optionKinds":["correct","near-miss","wrong-punch","wrong-punch"],"correctIndex":0},
  {"difficulty":"Easy","folds":["left"],"punch":{"x":5,"y":4},"options":[[{"x":2,"y":4},{"x":4,"y":5}],[{"x":2,"y":5},{"x":5,"y":5}],[{"x":2,"y":4},{"x":5,"y":4}],[{"x":3,"y":4},{"x":4,"y":4}]],"optionKinds":["near-miss","wrong-punch","correct","wrong-punch"],"correctIndex":2},
  {"difficulty":"Easy","folds":["down"],"punch":{"x":0,"y":3},"options":[[{"x":1,"y":3},{"x":0,"y":4}],[{"x":0,"y":3},{"x":0,"y":4}],[{"x":1,"y":3},{"x":1,"y":4}],[{"x":0,"y":2},{"x":0,"y":5}]],"optionKinds":["near-miss","correct","wrong-punch","wrong-punch"],"correctIndex":1},
  {"difficulty":"Medium","folds":["left","up"],"punch":{"x":6,"y":4},"options":[[{"x":1,"y":3},{"x":6,"y":3},{"x":7,"y":3},{"x":1,"y":4}],[{"x":0,"y":3},{"x":7,"y":3},{"x":0,"y":4},{"x":7,"y":4}],[{"x":1,"y":3},{"x":6,"y":3},{"x":1,"y":4},{"x":6,"y":4}],[{"x":1,"y":2},{"x":6,"y":2},{"x":1,"y":5},{"x":6,"y":5}]],"optionKinds":["near-miss","wrong-punch","correct","wrong-punch"],"correctIndex":2},
  {"difficulty":"Medium","folds":["down","right"],"punch":{"x":1,"y":1},"options":[[{"x":1,"y":1},{"x":6,"y":1},{"x":1,"y":6},{"x":6,"y":6}],[{"x":1,"y":1},{"x":6,"y":1},{"x":0,"y":5},{"x":6,"y":6}],[{"x":0,"y":1},{"x":7,"y":1},{"x":0,"y":6},{"x":7,"y":6}],[{"x":1,"y":0},{"x":6,"y":0},{"x":1,"y":7},{"x":6,"y":7}]],"optionKinds":["correct","near-miss","wrong-punch","wrong-punch"],"correctIndex":0},
  {"difficulty":"Medium","folds":["down","right"],"punch":{"x":2,"y":2},"options":[[{"x":2,"y":2},{"x":5,"y":2},{"x":1,"y":4},{"x":5,"y":5}],[{"x":1,"y":2},{"x":6,"y":2},{"x":1,"y":5},{"x":6,"y":5}],[{"x":2,"y":1},{"x":5,"y":1},{"x":2,"y":6},{"x":5,"y":6}],[{"x":2,"y":2},{"x":5,"y":2},{"x":2,"y":5},{"x":5,"y":5}]],"optionKinds":["near-miss","wrong-punch","wrong-punch","correct"],"correctIndex":3},
  {"difficulty":"Medium","folds":["up","right"],"punch":{"x":0,"y":4},"options":[[{"x":0,"y":3},{"x":7,"y":3},{"x":7,"y":4},{"x":1,"y":5}],[{"x":0,"y":3},{"x":7,"y":3},{"x":0,"y":4},{"x":7,"y":4}],[{"x":1,"y":3},{"x":6,"y":3},{"x":1,"y":4},{"x":6,"y":4}],[{"x":0,"y":2},{"x":7,"y":2},{"x":0,"y":5},{"x":7,"y":5}]],"optionKinds":["near-miss","correct","wrong-punch","wrong-punch"],"correctIndex":1},
  {"difficulty":"Medium","folds":["up","left"],"punch":{"x":7,"y":7},"options":[[{"x":0,"y":0},{"x":7,"y":0},{"x":0,"y":7},{"x":7,"y":7}],[{"x":1,"y":0},{"x":7,"y":0},{"x":0,"y":7},{"x":7,"y":7}],[{"x":1,"y":0},{"x":6,"y":0},{"x":1,"y":7},{"x":6,"y":7}],[{"x":0,"y":1},{"x":7,"y":1},{"x":0,"y":6},{"x":7,"y":6}]],"optionKinds":["correct","near-miss","wrong-punch","wrong-punch"],"correctIndex":0},
  {"difficulty":"Medium","folds":["right","up"],"punch":{"x":3,"y":4},"options":[[{"x":4,"y":2},{"x":3,"y":3},{"x":3,"y":4},{"x":4,"y":4}],[{"x":2,"y":3},{"x":5,"y":3},{"x":2,"y":4},{"x":5,"y":4}],[{"x":3,"y":3},{"x":4,"y":3},{"x":3,"y":4},{"x":4,"y":4}],[{"x":3,"y":2},{"x":4,"y":2},{"x":3,"y":5},{"x":4,"y":5}]],"optionKinds":["near-miss","wrong-punch","correct","wrong-punch"],"correctIndex":2},
  {"difficulty":"Medium","folds":["left","left"],"punch":{"x":7,"y":3},"options":[[{"x":1,"y":3},{"x":3,"y":3},{"x":4,"y":3},{"x":7,"y":3}],[{"x":0,"y":3},{"x":3,"y":3},{"x":4,"y":3},{"x":7,"y":3}],[{"x":1,"y":3},{"x":2,"y":3},{"x":5,"y":3},{"x":6,"y":3}],[{"x":0,"y":2},{"x":3,"y":2},{"x":4,"y":2},{"x":7,"y":2}]],"optionKinds":["near-miss","correct","wrong-punch","wrong-punch"],"correctIndex":1},
  {"difficulty":"Medium","folds":["down","left"],"punch":{"x":7,"y":1},"options":[[{"x":0,"y":1},{"x":7,"y":2},{"x":0,"y":6},{"x":7,"y":6}],[{"x":1,"y":1},{"x":6,"y":1},{"x":1,"y":6},{"x":6,"y":6}],[{"x":0,"y":0},{"x":7,"y":0},{"x":0,"y":7},{"x":7,"y":7}],[{"x":0,"y":1},{"x":7,"y":1},{"x":0,"y":6},{"x":7,"y":6}]],"optionKinds":["near-miss","wrong-punch","wrong-punch","correct"],"correctIndex":3},
  {"difficulty":"Medium","folds":["right","up"],"punch":{"x":0,"y":6},"options":[[{"x":0,"y":1},{"x":6,"y":2},{"x":0,"y":6},{"x":7,"y":6}],[{"x":0,"y":1},{"x":7,"y":1},{"x":0,"y":6},{"x":7,"y":6}],[{"x":0,"y":2},{"x":7,"y":2},{"x":0,"y":5},{"x":7,"y":5}],[{"x":1,"y":1},{"x":6,"y":1},{"x":1,"y":6},{"x":6,"y":6}]],"optionKinds":["near-miss","correct","wrong-punch","wrong-punch"],"correctIndex":1},
  {"difficulty":"Medium","folds":["right","down"],"punch":{"x":3,"y":1},"options":[[{"x":3,"y":1},{"x":4,"y":1},{"x":4,"y":5},{"x":3,"y":6}],[{"x":2,"y":1},{"x":5,"y":1},{"x":2,"y":6},{"x":5,"y":6}],[{"x":3,"y":0},{"x":4,"y":0},{"x":3,"y":7},{"x":4,"y":7}],[{"x":3,"y":1},{"x":4,"y":1},{"x":3,"y":6},{"x":4,"y":6}]],"optionKinds":["near-miss","wrong-punch","wrong-punch","correct"],"correctIndex":3},
  {"difficulty":"Medium","folds":["right","up"],"punch":{"x":0,"y":7},"options":[[{"x":0,"y":0},{"x":7,"y":0},{"x":0,"y":7},{"x":7,"y":7}],[{"x":0,"y":0},{"x":7,"y":0},{"x":0,"y":7},{"x":6,"y":7}],[{"x":0,"y":1},{"x":7,"y":1},{"x":0,"y":6},{"x":7,"y":6}],[{"x":1,"y":0},{"x":6,"y":0},{"x":1,"y":7},{"x":6,"y":7}]],"optionKinds":["correct","near-miss","wrong-punch","wrong-punch"],"correctIndex":0},
  {"difficulty":"Medium","folds":["left","up"],"punch":{"x":5,"y":4},"options":[[{"x":2,"y":3},{"x":5,"y":3},{"x":2,"y":4},{"x":6,"y":5}],[{"x":3,"y":3},{"x":4,"y":3},{"x":3,"y":4},{"x":4,"y":4}],[{"x":2,"y":3},{"x":5,"y":3},{"x":2,"y":4},{"x":5,"y":4}],[{"x":1,"y":3},{"x":6,"y":3},{"x":1,"y":4},{"x":6,"y":4}]],"optionKinds":["near-miss","wrong-punch","correct","wrong-punch"],"correctIndex":2},
  {"difficulty":"Hard","folds":["down","left","down"],"punch":{"x":4,"y":0},"options":[[{"x":3,"y":0},{"x":4,"y":0},{"x":3,"y":3},{"x":4,"y":3},{"x":3,"y":4},{"x":4,"y":4},{"x":5,"y":6},{"x":3,"y":7}],[{"x":3,"y":0},{"x":4,"y":0},{"x":3,"y":3},{"x":4,"y":3},{"x":3,"y":4},{"x":4,"y":4},{"x":3,"y":7},{"x":4,"y":7}],[{"x":3,"y":1},{"x":4,"y":1},{"x":3,"y":2},{"x":4,"y":2},{"x":3,"y":5},{"x":4,"y":5},{"x":3,"y":6},{"x":4,"y":6}],[{"x":2,"y":0},{"x":5,"y":0},{"x":2,"y":3},{"x":5,"y":3},{"x":2,"y":4},{"x":5,"y":4},{"x":2,"y":7},{"x":5,"y":7}]],"optionKinds":["near-miss","correct","wrong-punch","wrong-punch"],"correctIndex":1},
  {"difficulty":"Hard","folds":["right","down","up"],"punch":{"x":0,"y":2},"options":[[{"x":1,"y":1},{"x":7,"y":1},{"x":0,"y":2},{"x":7,"y":2},{"x":0,"y":5},{"x":7,"y":5},{"x":0,"y":6},{"x":7,"y":6}],[{"x":1,"y":1},{"x":6,"y":1},{"x":1,"y":2},{"x":6,"y":2},{"x":1,"y":5},{"x":6,"y":5},{"x":1,"y":6},{"x":6,"y":6}],[{"x":0,"y":0},{"x":7,"y":0},{"x":0,"y":3},{"x":7,"y":3},{"x":0,"y":4},{"x":7,"y":4},{"x":0,"y":7},{"x":7,"y":7}],[{"x":0,"y":1},{"x":7,"y":1},{"x":0,"y":2},{"x":7,"y":2},{"x":0,"y":5},{"x":7,"y":5},{"x":0,"y":6},{"x":7,"y":6}]],"optionKinds":["near-miss","wrong-punch","wrong-punch","correct"],"correctIndex":3},
  {"difficulty":"Hard","folds":["left","down","up"],"punch":{"x":6,"y":2},"options":[[{"x":1,"y":1},{"x":6,"y":1},{"x":1,"y":2},{"x":6,"y":2},{"x":1,"y":5},{"x":6,"y":5},{"x":1,"y":6},{"x":6,"y":6}],[{"x":2,"y":1},{"x":6,"y":1},{"x":1,"y":2},{"x":6,"y":2},{"x":1,"y":5},{"x":6,"y":5},{"x":1,"y":6},{"x":6,"y":6}],[{"x":2,"y":1},{"x":5,"y":1},{"x":2,"y":2},{"x":5,"y":2},{"x":2,"y":5},{"x":5,"y":5},{"x":2,"y":6},{"x":5,"y":6}],[{"x":0,"y":1},{"x":7,"y":1},{"x":0,"y":2},{"x":7,"y":2},{"x":0,"y":5},{"x":7,"y":5},{"x":0,"y":6},{"x":7,"y":6}]],"optionKinds":["correct","near-miss","wrong-punch","wrong-punch"],"correctIndex":0},
  {"difficulty":"Hard","folds":["left","up","right"],"punch":{"x":5,"y":7},"options":[[{"x":1,"y":0},{"x":2,"y":0},{"x":5,"y":0},{"x":6,"y":0},{"x":0,"y":6},{"x":2,"y":7},{"x":5,"y":7},{"x":6,"y":7}],[{"x":0,"y":0},{"x":3,"y":0},{"x":4,"y":0},{"x":7,"y":0},{"x":0,"y":7},{"x":3,"y":7},{"x":4,"y":7},{"x":7,"y":7}],[{"x":1,"y":0},{"x":2,"y":0},{"x":5,"y":0},{"x":6,"y":0},{"x":1,"y":7},{"x":2,"y":7},{"x":5,"y":7},{"x":6,"y":7}],[{"x":1,"y":1},{"x":2,"y":1},{"x":5,"y":1},{"x":6,"y":1},{"x":1,"y":6},{"x":2,"y":6},{"x":5,"y":6},{"x":6,"y":6}]],"optionKinds":["near-miss","wrong-punch","correct","wrong-punch"],"correctIndex":2},
  {"difficulty":"Hard","folds":["up","left","down"],"punch":{"x":7,"y":4},"options":[[{"x":0,"y":0},{"x":7,"y":0},{"x":7,"y":2},{"x":0,"y":3},{"x":0,"y":4},{"x":7,"y":4},{"x":0,"y":7},{"x":7,"y":7}],[{"x":1,"y":0},{"x":6,"y":0},{"x":1,"y":3},{"x":6,"y":3},{"x":1,"y":4},{"x":6,"y":4},{"x":1,"y":7},{"x":6,"y":7}],[{"x":0,"y":1},{"x":7,"y":1},{"x":0,"y":2},{"x":7,"y":2},{"x":0,"y":5},{"x":7,"y":5},{"x":0,"y":6},{"x":7,"y":6}],[{"x":0,"y":0},{"x":7,"y":0},{"x":0,"y":3},{"x":7,"y":3},{"x":0,"y":4},{"x":7,"y":4},{"x":0,"y":7},{"x":7,"y":7}]],"optionKinds":["near-miss","wrong-punch","wrong-punch","correct"],"correctIndex":3},
  {"difficulty":"Hard","folds":["down","left","down"],"punch":{"x":5,"y":0},"options":[[{"x":2,"y":0},{"x":5,"y":0},{"x":5,"y":2},{"x":2,"y":3},{"x":2,"y":4},{"x":5,"y":4},{"x":2,"y":7},{"x":5,"y":7}],[{"x":2,"y":0},{"x":5,"y":0},{"x":2,"y":3},{"x":5,"y":3},{"x":2,"y":4},{"x":5,"y":4},{"x":2,"y":7},{"x":5,"y":7}],[{"x":3,"y":0},{"x":4,"y":0},{"x":3,"y":3},{"x":4,"y":3},{"x":3,"y":4},{"x":4,"y":4},{"x":3,"y":7},{"x":4,"y":7}],[{"x":1,"y":0},{"x":6,"y":0},{"x":1,"y":3},{"x":6,"y":3},{"x":1,"y":4},{"x":6,"y":4},{"x":1,"y":7},{"x":6,"y":7}]],"optionKinds":["near-miss","correct","wrong-punch","wrong-punch"],"correctIndex":1},
  {"difficulty":"Hard","folds":["left","down","left"],"punch":{"x":7,"y":0},"options":[[{"x":0,"y":0},{"x":4,"y":0},{"x":7,"y":0},{"x":3,"y":1},{"x":0,"y":7},{"x":3,"y":7},{"x":4,"y":7},{"x":7,"y":7}],[{"x":1,"y":0},{"x":2,"y":0},{"x":5,"y":0},{"x":6,"y":0},{"x":1,"y":7},{"x":2,"y":7},{"x":5,"y":7},{"x":6,"y":7}],[{"x":0,"y":0},{"x":3,"y":0},{"x":4,"y":0},{"x":7,"y":0},{"x":0,"y":7},{"x":3,"y":7},{"x":4,"y":7},{"x":7,"y":7}],[{"x":0,"y":1},{"x":3,"y":1},{"x":4,"y":1},{"x":7,"y":1},{"x":0,"y":6},{"x":3,"y":6},{"x":4,"y":6},{"x":7,"y":6}]],"optionKinds":["near-miss","wrong-punch","correct","wrong-punch"],"correctIndex":2},
  {"difficulty":"Hard","folds":["down","left","down"],"punch":{"x":5,"y":1},"options":[[{"x":2,"y":1},{"x":5,"y":1},{"x":2,"y":2},{"x":5,"y":2},{"x":2,"y":5},{"x":5,"y":5},{"x":2,"y":6},{"x":5,"y":6}],[{"x":2,"y":1},{"x":4,"y":1},{"x":2,"y":2},{"x":5,"y":2},{"x":2,"y":5},{"x":5,"y":5},{"x":2,"y":6},{"x":5,"y":6}],[{"x":2,"y":0},{"x":5,"y":0},{"x":2,"y":3},{"x":5,"y":3},{"x":2,"y":4},{"x":5,"y":4},{"x":2,"y":7},{"x":5,"y":7}],[{"x":1,"y":1},{"x":6,"y":1},{"x":1,"y":2},{"x":6,"y":2},{"x":1,"y":5},{"x":6,"y":5},{"x":1,"y":6},{"x":6,"y":6}]],"optionKinds":["correct","near-miss","wrong-punch","wrong-punch"],"correctIndex":0},
  {"difficulty":"Hard","folds":["left","down","up"],"punch":{"x":5,"y":3},"options":[[{"x":2,"y":0},{"x":5,"y":0},{"x":2,"y":3},{"x":5,"y":3},{"x":5,"y":4},{"x":3,"y":5},{"x":2,"y":7},{"x":5,"y":7}],[{"x":1,"y":0},{"x":6,"y":0},{"x":1,"y":3},{"x":6,"y":3},{"x":1,"y":4},{"x":6,"y":4},{"x":1,"y":7},{"x":6,"y":7}],[{"x":2,"y":0},{"x":5,"y":0},{"x":2,"y":3},{"x":5,"y":3},{"x":2,"y":4},{"x":5,"y":4},{"x":2,"y":7},{"x":5,"y":7}],[{"x":3,"y":0},{"x":4,"y":0},{"x":3,"y":3},{"x":4,"y":3},{"x":3,"y":4},{"x":4,"y":4},{"x":3,"y":7},{"x":4,"y":7}]],"optionKinds":["near-miss","wrong-punch","correct","wrong-punch"],"correctIndex":2},
  {"difficulty":"Hard","folds":["left","up","right"],"punch":{"x":4,"y":4},"options":[[{"x":0,"y":3},{"x":3,"y":3},{"x":4,"y":3},{"x":7,"y":3},{"x":0,"y":4},{"x":3,"y":4},{"x":4,"y":4},{"x":7,"y":4}],[{"x":1,"y":3},{"x":3,"y":3},{"x":4,"y":3},{"x":7,"y":3},{"x":0,"y":4},{"x":3,"y":4},{"x":4,"y":4},{"x":7,"y":4}],[{"x":1,"y":3},{"x":2,"y":3},{"x":5,"y":3},{"x":6,"y":3},{"x":1,"y":4},{"x":2,"y":4},{"x":5,"y":4},{"x":6,"y":4}],[{"x":0,"y":2},{"x":3,"y":2},{"x":4,"y":2},{"x":7,"y":2},{"x":0,"y":5},{"x":3,"y":5},{"x":4,"y":5},{"x":7,"y":5}]],"optionKinds":["correct","near-miss","wrong-punch","wrong-punch"],"correctIndex":0},
  {"difficulty":"Hard","folds":["up","right","left"],"punch":{"x":2,"y":6},"options":[[{"x":1,"y":1},{"x":2,"y":1},{"x":5,"y":1},{"x":6,"y":1},{"x":2,"y":6},{"x":5,"y":6},{"x":6,"y":6},{"x":2,"y":7}],[{"x":1,"y":0},{"x":2,"y":0},{"x":5,"y":0},{"x":6,"y":0},{"x":1,"y":7},{"x":2,"y":7},{"x":5,"y":7},{"x":6,"y":7}],[{"x":1,"y":2},{"x":2,"y":2},{"x":5,"y":2},{"x":6,"y":2},{"x":1,"y":5},{"x":2,"y":5},{"x":5,"y":5},{"x":6,"y":5}],[{"x":1,"y":1},{"x":2,"y":1},{"x":5,"y":1},{"x":6,"y":1},{"x":1,"y":6},{"x":2,"y":6},{"x":5,"y":6},{"x":6,"y":6}]],"optionKinds":["near-miss","wrong-punch","wrong-punch","correct"],"correctIndex":3},
  {"difficulty":"Hard","folds":["down","left","right"],"punch":{"x":5,"y":0},"options":[[{"x":1,"y":0},{"x":5,"y":0},{"x":6,"y":0},{"x":2,"y":1},{"x":1,"y":7},{"x":2,"y":7},{"x":5,"y":7},{"x":6,"y":7}],[{"x":1,"y":0},{"x":2,"y":0},{"x":5,"y":0},{"x":6,"y":0},{"x":1,"y":7},{"x":2,"y":7},{"x":5,"y":7},{"x":6,"y":7}],[{"x":0,"y":0},{"x":3,"y":0},{"x":4,"y":0},{"x":7,"y":0},{"x":0,"y":7},{"x":3,"y":7},{"x":4,"y":7},{"x":7,"y":7}],[{"x":1,"y":1},{"x":2,"y":1},{"x":5,"y":1},{"x":6,"y":1},{"x":1,"y":6},{"x":2,"y":6},{"x":5,"y":6},{"x":6,"y":6}]],"optionKinds":["near-miss","correct","wrong-punch","wrong-punch"],"correctIndex":1},
  {"difficulty":"Wizard","folds":["right","down","right"],"punch":{"x":1,"y":0},"options":[[{"x":1,"y":0},{"x":2,"y":0},{"x":5,"y":0},{"x":6,"y":0},{"x":1,"y":6},{"x":1,"y":7},{"x":5,"y":7},{"x":6,"y":7}],[{"x":0,"y":0},{"x":3,"y":0},{"x":4,"y":0},{"x":7,"y":0},{"x":0,"y":7},{"x":3,"y":7},{"x":4,"y":7},{"x":7,"y":7}],[{"x":1,"y":1},{"x":2,"y":1},{"x":5,"y":1},{"x":6,"y":1},{"x":1,"y":6},{"x":2,"y":6},{"x":5,"y":6},{"x":6,"y":6}],[{"x":1,"y":0},{"x":2,"y":0},{"x":5,"y":0},{"x":6,"y":0},{"x":1,"y":7},{"x":2,"y":7},{"x":5,"y":7},{"x":6,"y":7}]],"optionKinds":["near-miss","wrong-punch","wrong-punch","correct"],"correctIndex":3,"hiddenFoldIndex":1},
  {"difficulty":"Wizard","folds":["right","down","down"],"punch":{"x":1,"y":1},"options":[[{"x":1,"y":1},{"x":6,"y":1},{"x":1,"y":2},{"x":6,"y":2},{"x":6,"y":5},{"x":1,"y":6},{"x":2,"y":6},{"x":6,"y":6}],[{"x":1,"y":1},{"x":6,"y":1},{"x":1,"y":2},{"x":6,"y":2},{"x":1,"y":5},{"x":6,"y":5},{"x":1,"y":6},{"x":6,"y":6}],[{"x":0,"y":1},{"x":7,"y":1},{"x":0,"y":2},{"x":7,"y":2},{"x":0,"y":5},{"x":7,"y":5},{"x":0,"y":6},{"x":7,"y":6}],[{"x":1,"y":0},{"x":6,"y":0},{"x":1,"y":3},{"x":6,"y":3},{"x":1,"y":4},{"x":6,"y":4},{"x":1,"y":7},{"x":6,"y":7}]],"optionKinds":["near-miss","correct","wrong-punch","wrong-punch"],"correctIndex":1,"hiddenFoldIndex":1},
  {"difficulty":"Wizard","folds":["down","left","up"],"punch":{"x":5,"y":3},"options":[[{"x":2,"y":0},{"x":5,"y":1},{"x":2,"y":3},{"x":5,"y":3},{"x":2,"y":4},{"x":5,"y":4},{"x":2,"y":7},{"x":5,"y":7}],[{"x":1,"y":0},{"x":6,"y":0},{"x":1,"y":3},{"x":6,"y":3},{"x":1,"y":4},{"x":6,"y":4},{"x":1,"y":7},{"x":6,"y":7}],[{"x":2,"y":0},{"x":5,"y":0},{"x":2,"y":3},{"x":5,"y":3},{"x":2,"y":4},{"x":5,"y":4},{"x":2,"y":7},{"x":5,"y":7}],[{"x":3,"y":0},{"x":4,"y":0},{"x":3,"y":3},{"x":4,"y":3},{"x":3,"y":4},{"x":4,"y":4},{"x":3,"y":7},{"x":4,"y":7}]],"optionKinds":["near-miss","wrong-punch","correct","wrong-punch"],"correctIndex":2,"hiddenFoldIndex":2},
  {"difficulty":"Wizard","folds":["left","up","down"],"punch":{"x":5,"y":5},"options":[[{"x":2,"y":1},{"x":5,"y":1},{"x":2,"y":2},{"x":5,"y":2},{"x":2,"y":5},{"x":5,"y":5},{"x":2,"y":6},{"x":5,"y":6}],[{"x":2,"y":1},{"x":5,"y":1},{"x":1,"y":2},{"x":5,"y":2},{"x":2,"y":5},{"x":5,"y":5},{"x":2,"y":6},{"x":5,"y":6}],[{"x":2,"y":0},{"x":5,"y":0},{"x":2,"y":3},{"x":5,"y":3},{"x":2,"y":4},{"x":5,"y":4},{"x":2,"y":7},{"x":5,"y":7}],[{"x":1,"y":1},{"x":6,"y":1},{"x":1,"y":2},{"x":6,"y":2},{"x":1,"y":5},{"x":6,"y":5},{"x":1,"y":6},{"x":6,"y":6}]],"optionKinds":["correct","near-miss","wrong-punch","wrong-punch"],"correctIndex":0,"hiddenFoldIndex":0},
  {"difficulty":"Wizard","folds":["up","left","down"],"punch":{"x":6,"y":5},"options":[[{"x":1,"y":1},{"x":6,"y":1},{"x":0,"y":2},{"x":6,"y":2},{"x":1,"y":5},{"x":6,"y":5},{"x":1,"y":6},{"x":6,"y":6}],[{"x":1,"y":1},{"x":6,"y":1},{"x":1,"y":2},{"x":6,"y":2},{"x":1,"y":5},{"x":6,"y":5},{"x":1,"y":6},{"x":6,"y":6}],[{"x":2,"y":1},{"x":5,"y":1},{"x":2,"y":2},{"x":5,"y":2},{"x":2,"y":5},{"x":5,"y":5},{"x":2,"y":6},{"x":5,"y":6}],[{"x":1,"y":0},{"x":6,"y":0},{"x":1,"y":3},{"x":6,"y":3},{"x":1,"y":4},{"x":6,"y":4},{"x":1,"y":7},{"x":6,"y":7}]],"optionKinds":["near-miss","correct","wrong-punch","wrong-punch"],"correctIndex":1,"hiddenFoldIndex":1},
  {"difficulty":"Wizard","folds":["up","right","up"],"punch":{"x":2,"y":6},"options":[[{"x":2,"y":1},{"x":5,"y":1},{"x":2,"y":2},{"x":5,"y":2},{"x":2,"y":5},{"x":2,"y":6},{"x":4,"y":6},{"x":5,"y":6}],[{"x":1,"y":1},{"x":6,"y":1},{"x":1,"y":2},{"x":6,"y":2},{"x":1,"y":5},{"x":6,"y":5},{"x":1,"y":6},{"x":6,"y":6}],[{"x":3,"y":1},{"x":4,"y":1},{"x":3,"y":2},{"x":4,"y":2},{"x":3,"y":5},{"x":4,"y":5},{"x":3,"y":6},{"x":4,"y":6}],[{"x":2,"y":1},{"x":5,"y":1},{"x":2,"y":2},{"x":5,"y":2},{"x":2,"y":5},{"x":5,"y":5},{"x":2,"y":6},{"x":5,"y":6}]],"optionKinds":["near-miss","wrong-punch","wrong-punch","correct"],"correctIndex":3,"hiddenFoldIndex":2},
  {"difficulty":"Wizard","folds":["right","down","down"],"punch":{"x":2,"y":1},"options":[[{"x":2,"y":1},{"x":5,"y":1},{"x":2,"y":2},{"x":5,"y":2},{"x":2,"y":5},{"x":5,"y":5},{"x":2,"y":6},{"x":5,"y":6}],[{"x":2,"y":1},{"x":5,"y":1},{"x":2,"y":2},{"x":5,"y":2},{"x":1,"y":5},{"x":2,"y":5},{"x":5,"y":5},{"x":5,"y":6}],[{"x":2,"y":0},{"x":5,"y":0},{"x":2,"y":3},{"x":5,"y":3},{"x":2,"y":4},{"x":5,"y":4},{"x":2,"y":7},{"x":5,"y":7}],[{"x":3,"y":1},{"x":4,"y":1},{"x":3,"y":2},{"x":4,"y":2},{"x":3,"y":5},{"x":4,"y":5},{"x":3,"y":6},{"x":4,"y":6}]],"optionKinds":["correct","near-miss","wrong-punch","wrong-punch"],"correctIndex":0,"hiddenFoldIndex":1},
  {"difficulty":"Wizard","folds":["up","left","up"],"punch":{"x":7,"y":6},"options":[[{"x":0,"y":1},{"x":7,"y":1},{"x":0,"y":2},{"x":7,"y":2},{"x":7,"y":5},{"x":0,"y":6},{"x":1,"y":6},{"x":7,"y":6}],[{"x":0,"y":0},{"x":7,"y":0},{"x":0,"y":3},{"x":7,"y":3},{"x":0,"y":4},{"x":7,"y":4},{"x":0,"y":7},{"x":7,"y":7}],[{"x":0,"y":1},{"x":7,"y":1},{"x":0,"y":2},{"x":7,"y":2},{"x":0,"y":5},{"x":7,"y":5},{"x":0,"y":6},{"x":7,"y":6}],[{"x":1,"y":1},{"x":6,"y":1},{"x":1,"y":2},{"x":6,"y":2},{"x":1,"y":5},{"x":6,"y":5},{"x":1,"y":6},{"x":6,"y":6}]],"optionKinds":["near-miss","wrong-punch","correct","wrong-punch"],"correctIndex":2,"hiddenFoldIndex":0},
  {"difficulty":"Wizard","folds":["down","left","left"],"punch":{"x":6,"y":1},"options":[[{"x":1,"y":1},{"x":2,"y":1},{"x":5,"y":1},{"x":6,"y":1},{"x":1,"y":6},{"x":2,"y":6},{"x":5,"y":6},{"x":6,"y":6}],[{"x":1,"y":1},{"x":2,"y":1},{"x":5,"y":1},{"x":6,"y":1},{"x":2,"y":6},{"x":5,"y":6},{"x":6,"y":6},{"x":2,"y":7}],[{"x":1,"y":0},{"x":2,"y":0},{"x":5,"y":0},{"x":6,"y":0},{"x":1,"y":7},{"x":2,"y":7},{"x":5,"y":7},{"x":6,"y":7}],[{"x":0,"y":1},{"x":3,"y":1},{"x":4,"y":1},{"x":7,"y":1},{"x":0,"y":6},{"x":3,"y":6},{"x":4,"y":6},{"x":7,"y":6}]],"optionKinds":["correct","near-miss","wrong-punch","wrong-punch"],"correctIndex":0,"hiddenFoldIndex":1},
  {"difficulty":"Wizard","folds":["down","left","right"],"punch":{"x":4,"y":0},"options":[[{"x":0,"y":0},{"x":3,"y":0},{"x":4,"y":0},{"x":7,"y":0},{"x":3,"y":6},{"x":0,"y":7},{"x":3,"y":7},{"x":7,"y":7}],[{"x":1,"y":0},{"x":2,"y":0},{"x":5,"y":0},{"x":6,"y":0},{"x":1,"y":7},{"x":2,"y":7},{"x":5,"y":7},{"x":6,"y":7}],[{"x":0,"y":0},{"x":3,"y":0},{"x":4,"y":0},{"x":7,"y":0},{"x":0,"y":7},{"x":3,"y":7},{"x":4,"y":7},{"x":7,"y":7}],[{"x":0,"y":1},{"x":3,"y":1},{"x":4,"y":1},{"x":7,"y":1},{"x":0,"y":6},{"x":3,"y":6},{"x":4,"y":6},{"x":7,"y":6}]],"optionKinds":["near-miss","wrong-punch","correct","wrong-punch"],"correctIndex":2,"hiddenFoldIndex":0},
  {"difficulty":"Wizard","folds":["right","up","right"],"punch":{"x":0,"y":6},"options":[[{"x":0,"y":1},{"x":4,"y":1},{"x":7,"y":1},{"x":3,"y":2},{"x":0,"y":6},{"x":3,"y":6},{"x":4,"y":6},{"x":7,"y":6}],[{"x":0,"y":1},{"x":3,"y":1},{"x":4,"y":1},{"x":7,"y":1},{"x":0,"y":6},{"x":3,"y":6},{"x":4,"y":6},{"x":7,"y":6}],[{"x":1,"y":1},{"x":2,"y":1},{"x":5,"y":1},{"x":6,"y":1},{"x":1,"y":6},{"x":2,"y":6},{"x":5,"y":6},{"x":6,"y":6}],[{"x":0,"y":0},{"x":3,"y":0},{"x":4,"y":0},{"x":7,"y":0},{"x":0,"y":7},{"x":3,"y":7},{"x":4,"y":7},{"x":7,"y":7}]],"optionKinds":["near-miss","correct","wrong-punch","wrong-punch"],"correctIndex":1,"hiddenFoldIndex":0},
  {"difficulty":"Wizard","folds":["right","up","right"],"punch":{"x":0,"y":7},"options":[[{"x":0,"y":0},{"x":3,"y":0},{"x":7,"y":0},{"x":5,"y":1},{"x":0,"y":7},{"x":3,"y":7},{"x":4,"y":7},{"x":7,"y":7}],[{"x":1,"y":0},{"x":2,"y":0},{"x":5,"y":0},{"x":6,"y":0},{"x":1,"y":7},{"x":2,"y":7},{"x":5,"y":7},{"x":6,"y":7}],[{"x":0,"y":1},{"x":3,"y":1},{"x":4,"y":1},{"x":7,"y":1},{"x":0,"y":6},{"x":3,"y":6},{"x":4,"y":6},{"x":7,"y":6}],[{"x":0,"y":0},{"x":3,"y":0},{"x":4,"y":0},{"x":7,"y":0},{"x":0,"y":7},{"x":3,"y":7},{"x":4,"y":7},{"x":7,"y":7}]],"optionKinds":["near-miss","wrong-punch","wrong-punch","correct"],"correctIndex":3,"hiddenFoldIndex":2},
] as const satisfies readonly CampaignRoundSpec[];
