"""Local, auditable corpus-retrieval primitives."""

from .semantic import (
    DEFAULT_ARTIFACT_BASENAME,
    MISSING_STRATEGY_WARNING,
    SEMANTIC_DOCUMENT_SCHEMA_VERSION,
    SEMANTIC_INDEX_ALGORITHM_VERSION,
    SEMANTIC_INDEX_CONFIG_VERSION,
    SEMANTIC_INDEX_MANIFEST_VERSION,
    ComponentSimilarities,
    MutualKnnEdge,
    RetrievalView,
    RetrievalViewUnavailableError,
    SemanticArtifactError,
    SemanticArtifactManifest,
    SemanticArtifactPaths,
    SemanticDocument,
    SemanticIndex,
    SemanticIndexConfig,
    SemanticIndexError,
    SemanticNeighbor,
    SemanticQueryResult,
    StaleSemanticArtifactError,
    StrategyViewUnavailableError,
)

__all__ = [
    "DEFAULT_ARTIFACT_BASENAME",
    "MISSING_STRATEGY_WARNING",
    "SEMANTIC_DOCUMENT_SCHEMA_VERSION",
    "SEMANTIC_INDEX_ALGORITHM_VERSION",
    "SEMANTIC_INDEX_CONFIG_VERSION",
    "SEMANTIC_INDEX_MANIFEST_VERSION",
    "ComponentSimilarities",
    "MutualKnnEdge",
    "RetrievalView",
    "RetrievalViewUnavailableError",
    "SemanticArtifactError",
    "SemanticArtifactManifest",
    "SemanticArtifactPaths",
    "SemanticDocument",
    "SemanticIndex",
    "SemanticIndexConfig",
    "SemanticIndexError",
    "SemanticNeighbor",
    "SemanticQueryResult",
    "StaleSemanticArtifactError",
    "StrategyViewUnavailableError",
]
